# Generated by Django 5.0.2 on 2025-11-29 05:51

import app_movil_escolar_api.validatos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='alfanumerico_invalido', message='Solo se permiten letras, números y espacios. No se permiten caracteres especiales.', regex='^[a-zA-Z0-9 áéíóúüñÁÉÍÓÚÜÑ]+$')])),
                ('tipo', models.CharField(choices=[('conferencia', 'Conferencia'), ('taller', 'Taller'), ('seminario', 'Seminario'), ('concurso', 'Concurso')], max_length=50)),
                ('fecha', models.DateField(validators=[app_movil_escolar_api.validatos.validar_fecha_no_pasada])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='alfanumerico_invalido', message='Solo se permiten letras, números y espacios. No se permiten caracteres especiales.', regex='^[a-zA-Z0-9 áéíóúüñÁÉÍÓÚÜÑ]+$')])),
                ('publico_objectivo', models.CharField(choices=[('alumnos', 'Alumnos'), ('maestros', 'Maestros'), ('publico_general', 'Público General')], max_length=50)),
                ('programa_educativo', models.CharField(blank=True, choices=[('ingenieria_ciencias_computacion', 'Ingeniería en Ciencias de la Computación'), ('licenciatura_ciencias_computacion', 'Licenciatura en Ciencias de la Computación'), ('ingenieria_tecnologias_informacion', 'Ingeniería en Tecnologías de la Información')], max_length=50, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=300, validators=[django.core.validators.RegexValidator(code='puntuacion_invalida', message='Solo se permiten letras, números y signos de puntuación básicos.', regex='^[a-zA-Z0-9 áéíóúüñÁÉÍÓÚÜÑ.,\\-_]+$')])),
                ('cupo_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
            ],
        ),
    ]
