# Generated by Django 5.0.2 on 2025-11-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='publico_objectivo',
            new_name='publico_objetivo',
        ),
    ]
